/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.awt.Color;

/**
 *
 * @author ADMIN
 */
public class AdmiV extends javax.swing.JFrame {

    /**
     * Creates new form AdmiV
     */
    public AdmiV() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jP_cli = new javax.swing.JPanel();
        jP_emple = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtBusquedaDni = new javax.swing.JTextField();
        bntBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jP_estadis = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jP_estadisticas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jP_clientes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jP_empleados = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jP_cerrarses = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jBcerrar = new javax.swing.JButton();
        jLmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jP_cli.setForeground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jP_cliLayout = new javax.swing.GroupLayout(jP_cli);
        jP_cli.setLayout(jP_cliLayout);
        jP_cliLayout.setHorizontalGroup(
            jP_cliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jP_cliLayout.setVerticalGroup(
            jP_cliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        jP_emple.setBackground(new java.awt.Color(182, 215, 248));
        jP_emple.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Registro de Empleados");
        jP_emple.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 310, 33));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Datos del empleado");
        jP_emple.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombres:");
        jP_emple.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Apellidos:");
        jP_emple.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("DNI:");
        jP_emple.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Telefono:");
        jP_emple.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));
        jP_emple.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 140, -1));
        jP_emple.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 160, -1));
        jP_emple.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 120, -1));
        jP_emple.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 120, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Direccion:");
        jP_emple.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        jP_emple.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 250, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Correo:");
        jP_emple.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));
        jP_emple.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 220, -1));

        btnGuardar.setText("Guardar");
        jP_emple.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, -1, -1));

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jP_emple.add(jComboBoxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, -1, -1));

        btnEditar.setText("Editar");
        jP_emple.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-eliminar-25.png"))); // NOI18N
        btnEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEliminar.setOpaque(false);
        jP_emple.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, 30, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Buscar empleado por DNI:");
        jP_emple.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 350, 190, 20));
        jP_emple.add(txtBusquedaDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 140, -1));

        bntBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-buscar-30 (1).png"))); // NOI18N
        bntBuscar.setBorder(null);
        bntBuscar.setOpaque(false);
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });
        jP_emple.add(bntBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 30, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Apellidos", "Correo", "Telefono", "Direccion", "Cargo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jP_emple.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 910, 100));
        jP_emple.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 930, 10));

        jP_estadis.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jP_estadisLayout = new javax.swing.GroupLayout(jP_estadis);
        jP_estadis.setLayout(jP_estadisLayout);
        jP_estadisLayout.setHorizontalGroup(
            jP_estadisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jP_estadisLayout.setVerticalGroup(
            jP_estadisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_estadis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_emple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_cli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jP_estadis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jP_emple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jP_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 980, 550));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 110));

        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Bienvenido ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 160, 40));

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("trabajador");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 160, 40));

        jP_estadisticas.setBackground(new java.awt.Color(236, 153, 69));
        jP_estadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_estadisticasMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-ventas-30 (1).png"))); // NOI18N
        jLabel5.setText("Estadisticas");

        javax.swing.GroupLayout jP_estadisticasLayout = new javax.swing.GroupLayout(jP_estadisticas);
        jP_estadisticas.setLayout(jP_estadisticasLayout);
        jP_estadisticasLayout.setHorizontalGroup(
            jP_estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_estadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_estadisticasLayout.setVerticalGroup(
            jP_estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_estadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jP_estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 180, 60));

        jP_clientes.setBackground(new java.awt.Color(236, 153, 69));
        jP_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_clientesMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-clientes-30.png"))); // NOI18N
        jLabel3.setText("Clientes");

        javax.swing.GroupLayout jP_clientesLayout = new javax.swing.GroupLayout(jP_clientes);
        jP_clientes.setLayout(jP_clientesLayout);
        jP_clientesLayout.setHorizontalGroup(
            jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_clientesLayout.setVerticalGroup(
            jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jP_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 60));

        jP_empleados.setBackground(new java.awt.Color(236, 153, 69));
        jP_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_empleadosMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-empleado-30.png"))); // NOI18N
        jLabel4.setText("Empleados");

        javax.swing.GroupLayout jP_empleadosLayout = new javax.swing.GroupLayout(jP_empleados);
        jP_empleados.setLayout(jP_empleadosLayout);
        jP_empleadosLayout.setHorizontalGroup(
            jP_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_empleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_empleadosLayout.setVerticalGroup(
            jP_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_empleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jP_empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 60));

        jP_cerrarses.setBackground(new java.awt.Color(236, 153, 69));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cerrar-sesión-30.png"))); // NOI18N
        jLabel7.setText("Cerrar Sesión");

        javax.swing.GroupLayout jP_cerrarsesLayout = new javax.swing.GroupLayout(jP_cerrarses);
        jP_cerrarses.setLayout(jP_cerrarsesLayout);
        jP_cerrarsesLayout.setHorizontalGroup(
            jP_cerrarsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cerrarsesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jP_cerrarsesLayout.setVerticalGroup(
            jP_cerrarsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_cerrarsesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jP_cerrarses, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, 60));

        jBcerrar.setBackground(new java.awt.Color(243, 112, 24));
        jBcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cerrar-ventana-32.png"))); // NOI18N
        jBcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBcerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jBcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 30, 30));

        jLmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-menos-32.png"))); // NOI18N
        jLmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLminMouseClicked(evt);
            }
        });
        getContentPane().add(jLmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondomenu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLminMouseClicked
        this.setState(AdmiV.ICONIFIED);
    }//GEN-LAST:event_jLminMouseClicked

    private void jBcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBcerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jBcerrarMouseClicked

    private void jP_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_clientesMouseClicked
        jP_cli.setVisible(true);
        jP_emple.setVisible(false);
        jP_estadis.setVisible(false);
        jP_clientes.setBackground(Color.black);
        jP_empleados.setBackground(new Color(236,153,69));
        jP_estadisticas.setBackground(new Color(236,153,69));
    }//GEN-LAST:event_jP_clientesMouseClicked

    private void jP_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_empleadosMouseClicked
        jP_emple.setVisible(true);
        jP_cli.setVisible(false);
        jP_estadis.setVisible(false);
        jP_empleados.setBackground(Color.black);
        jP_clientes.setBackground(new Color(236,153,69));
        jP_estadisticas.setBackground(new Color(236,153,69));
    }//GEN-LAST:event_jP_empleadosMouseClicked

    private void jP_estadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_estadisticasMouseClicked
        jP_estadis.setVisible(true);
        jP_emple.setVisible(false);
        jP_cli.setVisible(false);
        jP_estadisticas.setBackground(Color.black);
        jP_empleados.setBackground(new Color(236,153,69));
        jP_clientes.setBackground(new Color(236,153,69));
    }//GEN-LAST:event_jP_estadisticasMouseClicked

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmiV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmiV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmiV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmiV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmiV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jBcerrar;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLmin;
    private javax.swing.JPanel jP_cerrarses;
    private javax.swing.JPanel jP_cli;
    private javax.swing.JPanel jP_clientes;
    private javax.swing.JPanel jP_emple;
    private javax.swing.JPanel jP_empleados;
    private javax.swing.JPanel jP_estadis;
    private javax.swing.JPanel jP_estadisticas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBusquedaDni;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
